# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ ss ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BASE_API_URL: ${{ secrets.BASE_API_URL }}
      KK: ${{ secrets.KK }}
      DIST_PATH: dist
      SS_BUILD_PATH: dist/ss_build
      SS_DISASSEMBLER_PATH: data/rwp_jp_dis
      PCK_GLOBAL_INI_PATH: data/rwp_jp_asm/pck.global.ini
      PCK_OUTPUT_NAME: SceneEN.pck
      SHEET_PROC_FOLDER:  dist/sheet

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: "2.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Proc data from sheet
      run: |
        python sheets.py "$BASE_API_URL" "$KK" "$SS_DISASSEMBLER_PATH/resources" "$SHEET_PROC_FOLDER"

    - name: Assembler
      run: |
        mkdir -p "$SS_BUILD_PATH"
        python main.py -multi -asm "$SS_DISASSEMBLER_PATH" "$SS_BUILD_PATH"

    - name: Rebuild PCK
      run: |
        cp -v "$PCK_GLOBAL_INI_PATH" "$SS_BUILD_PATH"
        python main.py -pack "$SS_BUILD_PATH" "$DIST_PATH/$PCK_OUTPUT_NAME"
        echo "===Result data==="
        ls "$DIST_PATH"
    
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          ./${{env.DIST_PATH}}/**/*.*